### ISSUE TITLE
Why is the triple value for a corresponding 'V' mask actually consulted

### ISSUE THREAD

**Issue by arlac77** [Symatem/SymatemJS#4]
Somehow *queryTriples* expects a valid symbol even at positions where 'V' is present

```js
backend.queryTriples(backend.constructor.queryMasks.VMM,[undefined,symbol2,symbol3])
```

```sh
(node:82706) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Function.namespaceOfSymbol (Symbol.mjs:116:32)
    at RustWasmBackend.queryTriples (RustWasmBackend.mjs:119:29)
    at queryTriples.next (<anonymous>)```

**Comment by Lichtso** [comment]
Because the function is only evaluated after its arguments are passed to WASM. So, you have to fill in the V parts of your query triple with e.g. Void symbols so that the function call doesn't break when trying to translate a symbol from JS to Rust.
